### ISSUE TITLE
Problem 26

### ISSUE THREAD

**Issue by rebordao** [jacobcvt12/project_euler#1]
I have a compact version to Problem 26.

The page http://mathworld.wolfram.com/DecimalExpansion.html
has many useful results about decimal expansion. Something that
stands out is "The number of digits in the repeating portion
of the decimal expansion of a rational number can also be found
directly from the multiplicative order of its denominator."

```
library(gmp)
nrs <- 1:999

get_multi_ord <- function(nr, base = 10L) {
  # Computes Multiplicative Orders
  return (which(mod.bigz(pow.bigz(base, 1:nr), nr) == 1L)[1])
}

# Gets d with the longest recurring cycle
print (which.max(sapply(nrs, get_multi_ord)))
```

**Comment by jacobcvt12** [comment]
Thanks @rebordao ! Looks interesting.

**Comment by rebordao** [comment]
I just wanted to add a different perspective to your solution. It's not a proper issue. Feel free to close it.
I am also going through the problems and made a repository at Github.
Cheers!

**Comment by jacobcvt12** [comment]
Feel free to add any other interesting links that you find!
